### ISSUE TITLE
Does appjsonify recognize math expressions  and incorporate the corresponding LaTeX code in its extracted text output? 

### ISSUE THREAD

**Issue by rybshik** [hitachi-nlp/appjsonify#1]
I would like to find out how appjsonify handles PDFs that  have math symbols and short LaTeX-generated mathematical expressions. 

This interest particularly applies to documents where standard text is intertwined with brief mathematical expressions. 

An example can be seen in the 'Introduction' section of the research paper available at [https://arxiv.org/pdf/2106.13823.pdf](https://arxiv.org/pdf/2106.13823.pdf)

Does appjsonify accurately recognize math expressions and incorporate the corresponding LaTeX code in its extracted text output? 

An instance of such an expression would be the "quantum cross entropy $S(\rho, \sigma) = -\tr(\rho \log \sigma)$"

**Comment by gucci-j** [comment]
Hi, thanks for your question.

> Does appjsonify accurately recognize math expressions and incorporate the corresponding LaTeX code in its extracted text output?

Unfortunately, appjsonify does not support the accurate recognition of mathematical expressions in default due to its complete reliance on pdfplumber. However, if you optionally design a module incorporating LaTeX scripts into a processing pipeline, you could achieve the desired behaviour.

Best,
Atsuki
